# Flipkart E-commerce Data Cleaning and Preprocessing

## 1. Setup and Library Imports

In [ ]:
import pandas as pd
import numpy as np
import re

## 2. Data Loading and Initial Inspection

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Data Science Project II/flipkart_com-ecommerce_sample.csv (1)/flipkart_com-ecommerce_sample.csv")
df.head()

,uniq_id,crawl_timestamp,product_url,product_name,product_category_tree,pid,retail_price,discounted_price,image,is_FK_Advantage_product,description,product_rating,overall_rating,brand,product_specifications
0,c2d766ca982eca8304150849735ffef9,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2FF9KEDEFGF,999.0,379.0,"[""http://img5a.flixcart.com/image/short/u/4/a/...",False,Key Features of Alisha Solid Women's Cycling S...,No rating available,No rating available,Alisha,"{""product_specification""=>[{""key""=>""Number of ..."
1,7f7036a6d550aaa89d34c77bd39a5e48,2016-03-25 22:59:23 +0000,http://www.flipkart.com/fabhomedecor-fabric-do...,FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",SBEEH3QGU7MFYJFY,32157.0,22646.0,"[""http://img6a.flixcart.com/image/sofa-bed/j/f...",False,FabHomeDecor Fabric Double Sofa Bed (Finish Co...,No rating available,No rating available,FabHomeDecor,"{""product_specification""=>[{""key""=>""Installati..."
2,f449ec65dcbc041b6ae5e6a32717d01b,2016-03-25 22:59:23 +0000,http://www.flipkart.com/aw-bellies/p/itmeh4grg...,AW Bellies,"[""Footwear >> Women's Footwear >> Ballerinas >...",SHOEH4GRSUBJGZXE,999.0,499.0,"[""http://img5a.flixcart.com/image/shoe/7/z/z/r...",False,Key Features of AW Bellies Sandals Wedges Heel...,No rating available,No rating available,AW,"{""product_specification""=>[{""key""=>""Ideal For""..."
3,0973b37acd0c664e3de26e97e5571454,2016-03-25 22:59:23 +0000,http://www.flipkart.com/alisha-solid-women-s-c...,Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",SRTEH2F6HUZMQ6SJ,699.0,267.0,"[""http://img5a.flixcart.com/image/short/6/2/h/...",False,Key Features of Alisha Solid Women's Cycling S...,No rating available,No rating available,Alisha,"{""product_specification""=>[{""key""=>""Number of ..."
4,bc940ea42ee6bef5ac7cea3fb5cfbee7,2016-03-25 22:59:23 +0000,http://www.flipkart.com/sicons-all-purpose-arn...,Sicons All Purpose Arnica Dog Shampoo,"[""Pet Supplies >> Grooming >> Skin & Coat Care...",PSOEH3ZYDMSYARJ5,220.0,210.0,"[""http://img5a.flixcart.com/image/pet-shampoo/...",False,Specifications of Sicons All Purpose Arnica Do...,No rating available,No rating available,Sicons,"{""product_specification""=>[{""key""=>""Pet Type"",..."

### Check Data Shape

In [ ]:
print(df.shape)

(20002, 15)

### Get Data Information and Column Types

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20002 entries, 0 to 20001
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   uniq_id                  20000 non-null  object
 1   crawl_timestamp          20000 non-null  object
 2   product_url              20000 non-null  object
 3   product_name             20000 non-null  object
 4   product_category_tree    20000 non-null  object
 5   pid                      20000 non-null  object
 6   retail_price             19922 non-null  float64
 7   discounted_price         19922 non-null  float64
 8   image                    19997 non-null  object
 9   is_FK_Advantage_product  20000 non-null  object
 10  description              19998 non-null  object
 11  product_rating           20000 non-null  object
 12  overall_rating           20000 non-null  object
 13  brand                    14136 non-null  object
 14  product_specifications   19986 non-null  object
dtypes: float64(2), object(13)
memory usage: 2.3+ MB

## 3. Column Selection

In [ ]:
# selectin only important column
df = df[['uniq_id', 'image', 'product_name', 'product_category_tree', 'description', 'brand', 'retail_price','discounted_price','product_rating']]
df

,uniq_id,image,product_name,product_category_tree,description,brand,retail_price,discounted_price,product_rating
0,c2d766ca982eca8304150849735ffef9,"[""http://img5a.flixcart.com/image/short/u/4/a/...",Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",Key Features of Alisha Solid Women's Cycling S...,Alisha,999.0,379.0,No rating available
1,7f7036a6d550aaa89d34c77bd39a5e48,"[""http://img6a.flixcart.com/image/sofa-bed/j/f...",FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",FabHomeDecor Fabric Double Sofa Bed (Finish Co...,FabHomeDecor,32157.0,22646.0,No rating available
2,f449ec65dcbc041b6ae5e6a32717d01b,"[""http://img5a.flixcart.com/image/shoe/7/z/z/r...",AW Bellies,"[""Footwear >> Women's Footwear >> Ballerinas >...",Key Features of AW Bellies Sandals Wedges Heel...,AW,999.0,499.0,No rating available
3,0973b37acd0c664e3de26e97e5571454,"[""http://img5a.flixcart.com/image/short/6/2/h/...",Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",Key Features of Alisha Solid Women's Cycling S...,Alisha,699.0,267.0,No rating available
4,bc940ea42ee6bef5ac7cea3fb5cfbee7,"[""http://img5a.flixcart.com/image/pet-shampoo/...",Sicons All Purpose Arnica Dog Shampoo,"[""Pet Supplies >> Grooming >> Skin & Coat Care...",Specifications of Sicons All Purpose Arnica Do...,Sicons,220.0,210.0,No rating available
...,...,...,...,...,...,...,...,...,...
19997,93e9d343837400ce0d7980874ece471c,"[""http://img5a.flixcart.com/image/sticker/b/s/...",Elite Collection Medium Acrylic Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",Buy Elite Collection Medium Acrylic Sticker fo...,Elite Collection,1299.0,999.0,No rating available
19998,669e79b8fa5d9ae020841c0c97d5e935,"[""http://img5a.flixcart.com/image/sticker/4/2/...",Elite Collection Medium Acrylic Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",Buy Elite Collection Medium Acrylic Sticker fo...,Elite Collection,1499.0,1199.0,No rating available
19999,cb4fa87a874f715fff567f7b7b3be79c,"[""http://img6a.flixcart.com/image/sticker/z/k/...",Elite Collection Medium Acrylic Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",Buy Elite Collection Medium Acrylic Sticker fo...,Elite Collection,1499.0,999.0,No rating available
20000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 4. Handling Missing Values

In [ ]:
df.isnull().sum()

uniq_id                     2
image                       5
product_name                2
product_category_tree       2
description                 4
brand                    5866
retail_price               80
discounted_price           80
product_rating              2
dtype: int64

### Drop Rows with Key Missing Values

In [ ]:
# Drop the missing values from product_name, product_category_tree,description
df = df.dropna(subset=[
    'product_name',
    'product_category_tree',
    'description',
    'uniq_id',
    'image',
])

### Impute Missing Numerical and Categorical Values

In [ ]:
df.loc[:, 'retail_price'] = df['retail_price'].fillna(df['retail_price'].median())
df.loc[:, 'discounted_price'] = df['discounted_price'].fillna(df['discounted_price'].median())
df.loc[:, 'brand'] = df['brand'].fillna('Unknown')
df

,uniq_id,image,product_name,product_category_tree,description,brand,retail_price,discounted_price,product_rating
0,c2d766ca982eca8304150849735ffef9,"[""http://img5a.flixcart.com/image/short/u/4/a/...",Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",Key Features of Alisha Solid Women's Cycling S...,Alisha,999.0,379.0,No rating available
1,7f7036a6d550aaa89d34c77bd39a5e48,"[""http://img6a.flixcart.com/image/sofa-bed/j/f...",FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",FabHomeDecor Fabric Double Sofa Bed (Finish Co...,FabHomeDecor,32157.0,22646.0,No rating available
2,f449ec65dcbc041b6ae5e6a32717d01b,"[""http://img5a.flixcart.com/image/shoe/7/z/z/r...",AW Bellies,"[""Footwear >> Women's Footwear >> Ballerinas >...",Key Features of AW Bellies Sandals Wedges Heel...,AW,999.0,499.0,No rating available
3,0973b37acd0c664e3de26e97e5571454,"[""http://img5a.flixcart.com/image/short/6/2/h/...",Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",Key Features of Alisha Solid Women's Cycling S...,Alisha,699.0,267.0,No rating available
4,bc940ea42ee6bef5ac7cea3fb5cfbee7,"[""http://img5a.flixcart.com/image/pet-shampoo/...",Sicons All Purpose Arnica Dog Shampoo,"[""Pet Supplies >> Grooming >> Skin & Coat Care...",Specifications of Sicons All Purpose Arnica Do...,Sicons,220.0,210.0,No rating available
...,...,...,...,...,...,...,...,...,...
19995,7179d2f6c4ad50a17d014ca1d2815156,"[""http://img6a.flixcart.com/image/wall-decorat...",WallDesign Small Vinyl Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",Buy WallDesign Small Vinyl Sticker for Rs.730 ...,WallDesign,1500.0,730.0,No rating available
19996,71ac419198359d37b8fe5e3fffdfee09,"[""http://img6a.flixcart.com/image/sticker/z/g/...",Wallmantra Large Vinyl Stickers Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",Buy Wallmantra Large Vinyl Stickers Sticker fo...,Wallmantra,1429.0,1143.0,No rating available
19997,93e9d343837400ce0d7980874ece471c,"[""http://img5a.flixcart.com/image/sticker/b/s/...",Elite Collection Medium Acrylic Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",Buy Elite Collection Medium Acrylic Sticker fo...,Elite Collection,1299.0,999.0,No rating available
19998,669e79b8fa5d9ae020841c0c97d5e935,"[""http://img5a.flixcart.com/image/sticker/4/2/...",Elite Collection Medium Acrylic Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",Buy Elite Collection Medium Acrylic Sticker fo...,Elite Collection,1499.0,1199.0,No rating available
19999,cb4fa87a874f715fff567f7b7b3be79c,"[""http://img6a.flixcart.com/image/sticker/z/k/...",Elite Collection Medium Acrylic Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",Buy Elite Collection Medium Acrylic Sticker fo...,Elite Collection,1499.0,999.0,No rating available

### Verify Missing Values After Handling

In [ ]:
df.isnull().sum()

uniq_id                  0
image                    0
product_name             0
product_category_tree    0
description              0
brand                    0
retail_price             0
discounted_price         0
product_rating           0
dtype: int64

## 5. Handling Duplicates

In [ ]:
df.duplicated(keep=False).sum()

np.int64(0)

### Confirm DataFrame Shape After Duplicate Removal

In [ ]:
df.drop_duplicates()

,uniq_id,image,product_name,product_category_tree,description,brand,retail_price,discounted_price,product_rating
0,c2d766ca982eca8304150849735ffef9,"[""http://img5a.flixcart.com/image/short/u/4/a/...",Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",Key Features of Alisha Solid Women's Cycling S...,Alisha,999.0,379.0,No rating available
1,7f7036a6d550aaa89d34c77bd39a5e48,"[""http://img6a.flixcart.com/image/sofa-bed/j/f...",FabHomeDecor Fabric Double Sofa Bed,"[""Furniture >> Living Room Furniture >> Sofa B...",FabHomeDecor Fabric Double Sofa Bed (Finish Co...,FabHomeDecor,32157.0,22646.0,No rating available
2,f449ec65dcbc041b6ae5e6a32717d01b,"[""http://img5a.flixcart.com/image/shoe/7/z/z/r...",AW Bellies,"[""Footwear >> Women's Footwear >> Ballerinas >...",Key Features of AW Bellies Sandals Wedges Heel...,AW,999.0,499.0,No rating available
3,0973b37acd0c664e3de26e97e5571454,"[""http://img5a.flixcart.com/image/short/6/2/h/...",Alisha Solid Women's Cycling Shorts,"[""Clothing >> Women's Clothing >> Lingerie, Sl...",Key Features of Alisha Solid Women's Cycling S...,Alisha,699.0,267.0,No rating available
4,bc940ea42ee6bef5ac7cea3fb5cfbee7,"[""http://img5a.flixcart.com/image/pet-shampoo/...",Sicons All Purpose Arnica Dog Shampoo,"[""Pet Supplies >> Grooming >> Skin & Coat Care...",Specifications of Sicons All Purpose Arnica Do...,Sicons,220.0,210.0,No rating available
...,...,...,...,...,...,...,...,...,...
19995,7179d2f6c4ad50a17d014ca1d2815156,"[""http://img6a.flixcart.com/image/wall-decorat...",WallDesign Small Vinyl Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",Buy WallDesign Small Vinyl Sticker for Rs.730 ...,WallDesign,1500.0,730.0,No rating available
19996,71ac419198359d37b8fe5e3fffdfee09,"[""http://img6a.flixcart.com/image/sticker/z/g/...",Wallmantra Large Vinyl Stickers Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",Buy Wallmantra Large Vinyl Stickers Sticker fo...,Wallmantra,1429.0,1143.0,No rating available
19997,93e9d343837400ce0d7980874ece471c,"[""http://img5a.flixcart.com/image/sticker/b/s/...",Elite Collection Medium Acrylic Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",Buy Elite Collection Medium Acrylic Sticker fo...,Elite Collection,1299.0,999.0,No rating available
19998,669e79b8fa5d9ae020841c0c97d5e935,"[""http://img5a.flixcart.com/image/sticker/4/2/...",Elite Collection Medium Acrylic Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",Buy Elite Collection Medium Acrylic Sticker fo...,Elite Collection,1499.0,1199.0,No rating available
19999,cb4fa87a874f715fff567f7b7b3be79c,"[""http://img6a.flixcart.com/image/sticker/z/k/...",Elite Collection Medium Acrylic Sticker,"[""Baby Care >> Baby & Kids Gifts >> Stickers >...",Buy Elite Collection Medium Acrylic Sticker fo...,Elite Collection,1499.0,999.0,No rating available

#### Display DataFrame Shape

In [ ]:
df.shape

(19995, 9)

### Display Data Types

In [ ]:
df.dtypes

uniq_id                   object
image                     object
product_name              object
product_category_tree     object
description               object
brand                     object
retail_price             float64
discounted_price         float64
product_rating            object
dtype: object

## 6. Cleaning Product Rating Column

In [ ]:
df['product_rating'].unique()

array(['No rating available', '5', '3', '3.6', '3.5', '4.4', '4', '1',
       '2.3', '4.8', '2.7', '4.5', '2.4', '3.2', '4.7', '2', '3.3', '4.3',
       '3.8', '4.2', '3.7', '3.9', '2.5', '3.1', '4.1', '3.4', '4.6',
       '1.5', '2.8', '2.9', '4.9', '2.2', '2.6', '1.3', '1.7', '1.8'],
      dtype=object)

### Count 'No rating available' entries

In [ ]:
count = (df['product_rating'] == "No rating available").sum()
print(count)

18146

### Drop Product Rating Column

In [ ]:
df = df.drop('product_rating', axis=1)

### Verify Data Types After Dropping 'product_rating'

In [ ]:
df.dtypes

uniq_id                   object
image                     object
product_name              object
product_category_tree     object
description               object
brand                     object
retail_price             float64
discounted_price         float64
dtype: object

## 7. Text Cleaning and Feature Engineering

In [ ]:
# cleaning the text function or text normalization
def clean_text(text):
    text = text.lower()                      # lowercase
    text = re.sub(r'<.*?>', '', text)        # remove HTML tags
    text = re.sub(r'[^a-z0-9 ]', ' ', text)  # remove special characters
    text = re.sub(r'\s+', ' ', text).strip() # remove extra spaces
    return text

### Apply Text Cleaning to Relevant Columns

In [ ]:
# Apply cleaning
df=df.copy()
df.loc[:, 'product_name'] = df['product_name'].fillna('').apply(clean_text)
df.loc[:, 'description'] = df['description'].fillna('').apply(clean_text)
df.loc[:, 'brand'] = df['brand'].fillna('').apply(clean_text)

# Extract category BEFORE cleaning it
df.loc[:, 'category'] = df['product_category_tree'] = df['product_category_tree'].str.replace(">>", " ", regex=False)
df.loc[:, 'category'] = df['category'].fillna('').apply(clean_text)
df

# We clean the text before combining it so that the final
#  product_text is already clean and consistent.

,uniq_id,image,product_name,product_category_tree,description,brand,retail_price,discounted_price,category
0,c2d766ca982eca8304150849735ffef9,"[""http://img5a.flixcart.com/image/short/u/4/a/...",alisha solid women s cycling shorts,"[""Clothing Women's Clothing Lingerie, Slee...",key features of alisha solid women s cycling s...,alisha,999.0,379.0,clothing women s clothing lingerie sleep swimw...
1,7f7036a6d550aaa89d34c77bd39a5e48,"[""http://img6a.flixcart.com/image/sofa-bed/j/f...",fabhomedecor fabric double sofa bed,"[""Furniture Living Room Furniture Sofa Bed...",fabhomedecor fabric double sofa bed finish col...,fabhomedecor,32157.0,22646.0,furniture living room furniture sofa beds futo...
2,f449ec65dcbc041b6ae5e6a32717d01b,"[""http://img5a.flixcart.com/image/shoe/7/z/z/r...",aw bellies,"[""Footwear Women's Footwear Ballerinas A...",key features of aw bellies sandals wedges heel...,aw,999.0,499.0,footwear women s footwear ballerinas aw bellies
3,0973b37acd0c664e3de26e97e5571454,"[""http://img5a.flixcart.com/image/short/6/2/h/...",alisha solid women s cycling shorts,"[""Clothing Women's Clothing Lingerie, Slee...",key features of alisha solid women s cycling s...,alisha,699.0,267.0,clothing women s clothing lingerie sleep swimw...
4,bc940ea42ee6bef5ac7cea3fb5cfbee7,"[""http://img5a.flixcart.com/image/pet-shampoo/...",sicons all purpose arnica dog shampoo,"[""Pet Supplies Grooming Skin & Coat Care ...",specifications of sicons all purpose arnica do...,sicons,220.0,210.0,pet supplies grooming skin coat care shampoo s...
...,...,...,...,...,...,...,...,...,...
19995,7179d2f6c4ad50a17d014ca1d2815156,"[""http://img6a.flixcart.com/image/wall-decorat...",walldesign small vinyl sticker,"[""Baby Care Baby & Kids Gifts Stickers W...",buy walldesign small vinyl sticker for rs 730 ...,walldesign,1500.0,730.0,baby care baby kids gifts stickers walldesign ...
19996,71ac419198359d37b8fe5e3fffdfee09,"[""http://img6a.flixcart.com/image/sticker/z/g/...",wallmantra large vinyl stickers sticker,"[""Baby Care Baby & Kids Gifts Stickers W...",buy wallmantra large vinyl stickers sticker fo...,wallmantra,1429.0,1143.0,baby care baby kids gifts stickers wallmantra ...
19997,93e9d343837400ce0d7980874ece471c,"[""http://img5a.flixcart.com/image/sticker/b/s/...",elite collection medium acrylic sticker,"[""Baby Care Baby & Kids Gifts Stickers E...",buy elite collection medium acrylic sticker fo...,elite collection,1299.0,999.0,baby care baby kids gifts stickers elite colle...
19998,669e79b8fa5d9ae020841c0c97d5e935,"[""http://img5a.flixcart.com/image/sticker/4/2/...",elite collection medium acrylic sticker,"[""Baby Care Baby & Kids Gifts Stickers E...",buy elite collection medium acrylic sticker fo...,elite collection,1499.0,1199.0,baby care baby kids gifts stickers elite colle...
19999,cb4fa87a874f715fff567f7b7b3be79c,"[""http://img6a.flixcart.com/image/sticker/z/k/...",elite collection medium acrylic sticker,"[""Baby Care Baby & Kids Gifts Stickers E...",buy elite collection medium acrylic sticker fo...,elite collection,1499.0,999.0,baby care baby kids gifts stickers elite colle...

### Drop Original Product Category Tree Column

In [ ]:
df.drop('product_category_tree', axis=1, inplace=True)
df

,uniq_id,image,product_name,description,brand,retail_price,discounted_price,category
0,c2d766ca982eca8304150849735ffef9,"[""http://img5a.flixcart.com/image/short/u/4/a/...",alisha solid women s cycling shorts,key features of alisha solid women s cycling s...,alisha,999.0,379.0,clothing women s clothing lingerie sleep swimw...
1,7f7036a6d550aaa89d34c77bd39a5e48,"[""http://img6a.flixcart.com/image/sofa-bed/j/f...",fabhomedecor fabric double sofa bed,fabhomedecor fabric double sofa bed finish col...,fabhomedecor,32157.0,22646.0,furniture living room furniture sofa beds futo...
2,f449ec65dcbc041b6ae5e6a32717d01b,"[""http://img5a.flixcart.com/image/shoe/7/z/z/r...",aw bellies,key features of aw bellies sandals wedges heel...,aw,999.0,499.0,footwear women s footwear ballerinas aw bellies
3,0973b37acd0c664e3de26e97e5571454,"[""http://img5a.flixcart.com/image/short/6/2/h/...",alisha solid women s cycling shorts,key features of alisha solid women s cycling s...,alisha,699.0,267.0,clothing women s clothing lingerie sleep swimw...
4,bc940ea42ee6bef5ac7cea3fb5cfbee7,"[""http://img5a.flixcart.com/image/pet-shampoo/...",sicons all purpose arnica dog shampoo,specifications of sicons all purpose arnica do...,sicons,220.0,210.0,pet supplies grooming skin coat care shampoo s...
...,...,...,...,...,...,...,...,...
19995,7179d2f6c4ad50a17d014ca1d2815156,"[""http://img6a.flixcart.com/image/wall-decorat...",walldesign small vinyl sticker,buy walldesign small vinyl sticker for rs 730 ...,walldesign,1500.0,730.0,baby care baby kids gifts stickers walldesign ...
19996,71ac419198359d37b8fe5e3fffdfee09,"[""http://img6a.flixcart.com/image/sticker/z/g/...",wallmantra large vinyl stickers sticker,buy wallmantra large vinyl stickers sticker fo...,wallmantra,1429.0,1143.0,baby care baby kids gifts stickers wallmantra ...
19997,93e9d343837400ce0d7980874ece471c,"[""http://img5a.flixcart.com/image/sticker/b/s/...",elite collection medium acrylic sticker,buy elite collection medium acrylic sticker fo...,elite collection,1299.0,999.0,baby care baby kids gifts stickers elite colle...
19998,669e79b8fa5d9ae020841c0c97d5e935,"[""http://img5a.flixcart.com/image/sticker/4/2/...",elite collection medium acrylic sticker,buy elite collection medium acrylic sticker fo...,elite collection,1499.0,1199.0,baby care baby kids gifts stickers elite colle...
19999,cb4fa87a874f715fff567f7b7b3be79c,"[""http://img6a.flixcart.com/image/sticker/z/k/...",elite collection medium acrylic sticker,buy elite collection medium acrylic sticker fo...,elite collection,1499.0,999.0,baby care baby kids gifts stickers elite colle...

### Combine Text Columns into a Single Feature

In [ ]:
df.loc[:, 'product_text'] = (
    df['product_name'].fillna('') + " " +
    df['description'].fillna('') + " " +
    df['category'].fillna('') + " " +
    df['brand'].fillna('')
)

df.loc[:, 'product_text'] = df['product_text'].apply(clean_text)
df

,uniq_id,image,product_name,description,brand,retail_price,discounted_price,category,product_text
0,c2d766ca982eca8304150849735ffef9,"[""http://img5a.flixcart.com/image/short/u/4/a/...",alisha solid women s cycling shorts,key features of alisha solid women s cycling s...,alisha,999.0,379.0,clothing women s clothing lingerie sleep swimw...,alisha solid women s cycling shorts key featur...
1,7f7036a6d550aaa89d34c77bd39a5e48,"[""http://img6a.flixcart.com/image/sofa-bed/j/f...",fabhomedecor fabric double sofa bed,fabhomedecor fabric double sofa bed finish col...,fabhomedecor,32157.0,22646.0,furniture living room furniture sofa beds futo...,fabhomedecor fabric double sofa bed fabhomedec...
2,f449ec65dcbc041b6ae5e6a32717d01b,"[""http://img5a.flixcart.com/image/shoe/7/z/z/r...",aw bellies,key features of aw bellies sandals wedges heel...,aw,999.0,499.0,footwear women s footwear ballerinas aw bellies,aw bellies key features of aw bellies sandals ...
3,0973b37acd0c664e3de26e97e5571454,"[""http://img5a.flixcart.com/image/short/6/2/h/...",alisha solid women s cycling shorts,key features of alisha solid women s cycling s...,alisha,699.0,267.0,clothing women s clothing lingerie sleep swimw...,alisha solid women s cycling shorts key featur...
4,bc940ea42ee6bef5ac7cea3fb5cfbee7,"[""http://img5a.flixcart.com/image/pet-shampoo/...",sicons all purpose arnica dog shampoo,specifications of sicons all purpose arnica do...,sicons,220.0,210.0,pet supplies grooming skin coat care shampoo s...,sicons all purpose arnica dog shampoo specific...
...,...,...,...,...,...,...,...,...,...
19995,7179d2f6c4ad50a17d014ca1d2815156,"[""http://img6a.flixcart.com/image/wall-decorat...",walldesign small vinyl sticker,buy walldesign small vinyl sticker for rs 730 ...,walldesign,1500.0,730.0,baby care baby kids gifts stickers walldesign ...,walldesign small vinyl sticker buy walldesign ...
19996,71ac419198359d37b8fe5e3fffdfee09,"[""http://img6a.flixcart.com/image/sticker/z/g/...",wallmantra large vinyl stickers sticker,buy wallmantra large vinyl stickers sticker fo...,wallmantra,1429.0,1143.0,baby care baby kids gifts stickers wallmantra ...,wallmantra large vinyl stickers sticker buy wa...
19997,93e9d343837400ce0d7980874ece471c,"[""http://img5a.flixcart.com/image/sticker/b/s/...",elite collection medium acrylic sticker,buy elite collection medium acrylic sticker fo...,elite collection,1299.0,999.0,baby care baby kids gifts stickers elite colle...,elite collection medium acrylic sticker buy el...
19998,669e79b8fa5d9ae020841c0c97d5e935,"[""http://img5a.flixcart.com/image/sticker/4/2/...",elite collection medium acrylic sticker,buy elite collection medium acrylic sticker fo...,elite collection,1499.0,1199.0,baby care baby kids gifts stickers elite colle...,elite collection medium acrylic sticker buy el...
19999,cb4fa87a874f715fff567f7b7b3be79c,"[""http://img6a.flixcart.com/image/sticker/z/k/...",elite collection medium acrylic sticker,buy elite collection medium acrylic sticker fo...,elite collection,1499.0,999.0,baby care baby kids gifts stickers elite colle...,elite collection medium acrylic sticker buy el...

## 8. Save Cleaned Data

In [ ]:
df.to_csv('cleaned_flipkart_data.csv', index=False)
print('DataFrame saved to cleaned_flipkart_data.csv')